# 对端遵循OneBot 11标准
[onebot]
address = "10.10.10.90"
port_http = 5700
port_wsv = 5800
# 机器人的QQ号
qq = 3684951062

# 接收&回复该群的消息
[group]
id = 300129041

# 定义存放外部Shell脚本的路径
[path]
all = '/home/tic/git/hard-realism-coop/r4s2/shell/all-servers'
rc = '/home/tic/git/hard-realism-coop/r4s2/shell/chunjing'
mpds = '/home/tic/git/hard-realism-coop/r4s2/shell/shichao'

# 定义供外部Shell生成临时文件的路径
[tmpfpath]
all = '/dev/shm/r4s2/all-servers'
rc = '/dev/shm/r4s2/rc'
mpds = '/dev/shm/r4s2/mpds'
