system("mkdir -p #{Config.path_rc('false')}/ServerInfoCollector/images/")
system("mkdir -p #{Config.path_mpds('false')}/ServerInfoCollector/images/")
system("mkdir -p #{Config.path_all('false')}")
system("echo #{Config.group_id} > /tmp/r4s2/target_group")
system("echo #{Config.path_rc('true')} > /tmp/r4s2/rc_shellpath")
system("echo #{Config.path_rc('false')} > /tmp/r4s2/rc_tmpfpath")
system("echo #{Config.path_mpds('true')} > /tmp/r4s2/mpds_shellpath")
system("echo #{Config.path_mpds('false')} > /tmp/r4s2/mpds_tmpfpath")
system("echo #{Config.path_all('true')} > /tmp/r4s2/all-servers_shellpath")
system("echo #{Config.path_all('false')} > /tmp/r4s2/all-servers_tmpfpath")
