char Fastdl_Files[][] = {
  "materials/models/headcrab/allinonebacup2.vmt",
  "materials/models/headcrab/allinonebacup2_normal.vtf",
  "materials/models/headcrab/allinonebacup2.vtf",
  "materials/models/headcrab/allinonebacup2_phong.vtf",
  "models/headcrab/jockey.ani",
  "models/headcrab/jockey.mdl",
  "models/headcrab/jockey.vvd",
  "models/headcrab/jockey.phy",
  "models/headcrab/jockey.dx90.vtx"
};

char Fastdl_Sounds[][] = {
  "rpp/headcrab/voice/death/jockey_death03.mp3",
  "rpp/headcrab/voice/death/jockey_death05.mp3",
  "rpp/headcrab/voice/death/jockey_death02.mp3",
  "rpp/headcrab/voice/death/jockey_death01.mp3",
  "rpp/headcrab/voice/death/jockey_death04.mp3",
  "rpp/headcrab/voice/death/jockey_death06.mp3",
  "rpp/headcrab/voice/attack/jockey_attackloop01.mp3",
  "rpp/headcrab/voice/attack/jockey_loudattack02.mp3",
  "rpp/headcrab/voice/attack/jockey_attackloop02.mp3",
  "rpp/headcrab/voice/attack/jockey_attackloop04.mp3",
  "rpp/headcrab/voice/attack/jockey_lurk02.mp3",
  "rpp/headcrab/voice/attack/jockey_attackloop03.mp3",
  "rpp/headcrab/voice/attack/jockey_loudattack01.mp3",
  "rpp/headcrab/voice/pain/jockey_pain03.mp3",
  "rpp/headcrab/voice/pain/jockey_pain05.mp3",
  "rpp/headcrab/voice/pain/jockey_pain06.mp3",
  "rpp/headcrab/voice/pain/jockey_painshort01.mp3",
  "rpp/headcrab/voice/pain/jockey_painshort05.mp3",
  "rpp/headcrab/voice/pain/jockey_painshort02.mp3",
  "rpp/headcrab/voice/pain/jockey_pain08.mp3",
  "rpp/headcrab/voice/pain/jockey_pain07.mp3",
  "rpp/headcrab/voice/pain/jockey_painshort04.mp3",
  "rpp/headcrab/voice/pain/jockey_pain01.mp3",
  "rpp/headcrab/voice/pain/jockey_pain04.mp3",
  "rpp/headcrab/voice/pain/jockey_painshort03.mp3",
  "rpp/headcrab/voice/pain/jockey_pain02.mp3",
  "rpp/headcrab/voice/warn/jockey_08.mp3",
  "rpp/headcrab/voice/warn/jockey_06.mp3"
};

