name: Build Linux and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Windows build
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Windows Environment: Install Scoop
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

      - name: Set up Windows Environment: Install Crystal
        shell: pwsh
        run: |
          scoop install git
          scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
          scoop install vs_2022_cpp_build_tools crystal

      - name: Execute build
        run: |
          crystal r4s2\client-cli\client.cr
          mv "r4s2\client-cli\client" "r4s2\client-cli\client-windows"

      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: r4s2\client-cli\client-windows.exe

  # Linux build
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Linux Environment
        run: |
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash

      - name: Execute build script
        run: |
          crystal r4s2/client-cli/client.cr
          mv r4s2/client-cli/client r4s2/client-cli/client-linux

      - name: Upload Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: r4s2/client-cli/client-linux
