name: Packaging Windows executable

on:
  push:
      paths:
        - 'r4s2/client-cli/**'

  workflow_dispatch:

jobs:
  # Windows build
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.193.0
        with:
            ruby-version: '3.3'

      - name: Install Gems
        run: |
          gem install ocran colorize cli-ui

      - name: Building an executable
        run: |
          ocran r4s2\client-cli\client-cli.rb --icon r4s2\client-cli\greenflu.icon --gem-all=digest/sha2 --output r4s2\client-cli\client-windows.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: r4s2\client-cli\client-windows.exe
