name: Packaging Windows executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Windows build
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.193.0
        with: 
            ruby-version: '3.3'

      - name: Install Ocran
        run: |
          gem install ocran

      - name: Building an executable
        run: |
          ocran r4s2\client-cli\client-cli.rb --output r4s2\client-cli\client-windows.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: r4s2\client-cli\client-windows.exe
