name: MapUploader

on:
#  push:
#      paths:
#        - 'uploader/client-cli/**'

  workflow_dispatch:

jobs:
  Windows-Binary:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 设置Ruby
        uses: ruby/setup-ruby@v1.193.0
        with:
            ruby-version: '3.3'

      - name: 安装必要的Gem
        run: |
          gem install ocran colorize cli-ui

      - name: 打包可执行文件
        run: |
          ocran uploader\client-cli\client-cli.rb --icon uploader\client-cli\greenflu.icon --gem-all=digest/sha2 --output uploader\client-cli\client-windows.241128-1.exe

      - name: 上传包裹
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary.241128-1
          path: uploader\client-cli\*.exe
