name: "Vanilla | Plugin Compiling Testing"
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "server/vanilla/SERVER_VERSION"
      
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  ENV-Packaging:
    runs-on: ubuntu-20.04
    output:
      devenv_name: ${{ steps.script.outputs.name }}
    steps:
      - name: 提取存储库
        uses: actions/checkout@v4

      - name: 执行脚本
        shell: bash
        id: script
        run: |
          mkdir action-tmp/ && cd action-tmp
          bash ../.github/scripts/vanilla/testing.sh $(pwd) "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          echo "FILE_NAME=$(cat PACKAGE_NAME)" >> $GITHUB_ENV
          rm PACKAGE_NAME
          echo "name=$FILE_NAME" >> "$GITHUB_OUTPUT"

      - name: 上传包裹
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }} 
          path: "*.tar.gz"
          compression-level: 0

  Plugin-Compiling:
    runs-on: ubuntu-20.04
    needs: ENV-Packaging
    steps:
      - name: 下载开发环境包
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.ENV-Packaging.outputs.devenv_name }}

      - name: 编译插件
        shell: bash
        env:
          NAME: ${{ needs.ENV-Packaging.outputs.devenv_name }} 
        run: |
          tar -xzvf $NAME.tar.gz && ls -lR && cd $NAME
          echo "####  ####"
          cd left4dead2/addons/sourcemod/scripting/
          ./compile.sh *.sp > log.txt
          cd compiled
          if grep -q " Error." ../log.txt; then
            echo "S # #" >> ../log.txt
            echo "E # #" >> ../log.txt
            find ../ >> ../log.txt
            exit 1
          fi

      - name: 上传日志
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: log
          path: left4dead2/addons/sourcemod/scripting/log.txt
 
