name:  "Server-Vanilla"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    paths:
      - 'server/vanilla/left4dead2/**'

#    paths-ignore:
#      - 'server/vanilla/'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  Setup:
    runs-on: ubuntu-20.04
    steps:
      - name: 提取存储库
        uses: actions/checkout@v4

      - name: 执行脚本
        shell: bash
        run: |
          cd server/vanilla/
          bash action-setup.sh "https://github.com/${{ github.repository }}/commit/${{ github.sha }}" "${{ secrets.GITHUB_TOKEN }}"
          if [ -e SCRIPT_FAIL ]; then
            exit -1
          fi
          # echo "FILE_NAME=$(cat PACKAGE_NAME)" >> $GITHUB_ENV

      - name: 上传包裹
        uses: actions/upload-artifact@v4
        with:
          name: devenv
          path: server/vanilla/devenv.tar.gz
          compression-level: 0

  Plugin-Compiling:
    runs-on: ubuntu-20.04
    needs: Setup
    steps:
      - name: 下载开发环境
        uses: actions/download-artifact@v4
        with:
          name: devenv

      - name: 编译插件
        shell: bash
        run: |
          tar -xzvf *.tar.gz && ls -lR && cd devenv
          cd left4dead2/addons/sourcemod/scripting/
          ./compile.sh *.sp > log
          cd compiled
          if grep -q " Error." ../log; then
            cat ../log
            find ../
            exit -1
          fi

  File-Packaging:
    runs-on: ubuntu-20.04
    environment:
      name: base

    needs: Plugin-Compiling
    steps:
      - name: 提取存储库
        uses: actions/checkout@v4

      - name: 下载开发环境
        uses: actions/download-artifact@v4
        with:
          name: devenv

      - name: 执行脚本
        shell: bash
        run: |
          tar -xzvf devenv.tar.gz  && cd devenv
          bash ../server/vanilla/action-full-package.sh
          echo "FILE_NAME=$TIMESTAMP" >> $GITHUB_ENV

      - name: 上传包裹
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: server/vanilla/package*.tar.gz
          compression-level: 0
